service: spanner
runtime: go113
instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.75
  target_throughput_utilization: 0.75
  max_instances: 5
  min_idle_instances: 0
  max_idle_instances: automatic  # default value
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 80

handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /static
  static_dir: static
- url: /swagger-ui
  static_dir: swagger-ui
- url: /.*
  script: auto